// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAy2Tc3TOIeiM5mV-orXj7DnvsAfdYkeLI',
    appId: '1:53574729538:web:fcc587f8b88180a88bd2db',
    messagingSenderId: '53574729538',
    projectId: 'coachmint-f5596',
    authDomain: 'coachmint-f5596.firebaseapp.com',
    storageBucket: 'coachmint-f5596.firebasestorage.app',
    measurementId: 'G-RS17Y4ZF50',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDr7M4w7lbMd-H02nvIESjQGfLgyKdjOh0',
    appId: '1:53574729538:android:3635ae9d56b61de48bd2db',
    messagingSenderId: '53574729538',
    projectId: 'coachmint-f5596',
    storageBucket: 'coachmint-f5596.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDLuWcmlENppGK12JBe0sXp5rRmuhuc-a0',
    appId: '1:53574729538:ios:27d290ed7f6fc6208bd2db',
    messagingSenderId: '53574729538',
    projectId: 'coachmint-f5596',
    storageBucket: 'coachmint-f5596.firebasestorage.app',
    iosBundleId: 'com.example.coachmint',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDLuWcmlENppGK12JBe0sXp5rRmuhuc-a0',
    appId: '1:53574729538:ios:27d290ed7f6fc6208bd2db',
    messagingSenderId: '53574729538',
    projectId: 'coachmint-f5596',
    storageBucket: 'coachmint-f5596.firebasestorage.app',
    iosBundleId: 'com.example.coachmint',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAy2Tc3TOIeiM5mV-orXj7DnvsAfdYkeLI',
    appId: '1:53574729538:web:5fc60408f65a73818bd2db',
    messagingSenderId: '53574729538',
    projectId: 'coachmint-f5596',
    authDomain: 'coachmint-f5596.firebaseapp.com',
    storageBucket: 'coachmint-f5596.firebasestorage.app',
    measurementId: 'G-YJBNWDV4K4',
  );
}
